CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS vector_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(768) NOT NULL,
    chunk_index INT NOT NULL,
    token_count INT NOT NULL,
    heading VARCHAR(500),
    source_file VARCHAR(500),
    category VARCHAR(100),
    audience VARCHAR(20) DEFAULT 'CUSTOMER' CHECK (audience IN ('CUSTOMER', 'INTERNAL', 'ADMIN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vector_chunks_document_id ON vector_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_vector_chunks_category ON vector_chunks(category);
CREATE INDEX IF NOT EXISTS idx_vector_chunks_created_at ON vector_chunks(created_at);
CREATE INDEX IF NOT EXISTS idx_vector_chunks_embedding ON vector_chunks USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_vector_chunks_content_fts
    ON vector_chunks
    USING gin (to_tsvector('english', content));
