CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(36),
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN ('QUESTION', 'ANSWER', 'FEEDBACK', 'ERROR', 'LOGIN', 'LOGOUT', 'DATA_DELETION', 'DOC_UPLOAD')),
    question_hash VARCHAR(64),
    doc_ids_retrieved JSONB,
    response_hash VARCHAR(64),
    tokens_used INT DEFAULT 0,
    latency_ms INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_event_type ON audit_log(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
