CREATE TABLE IF NOT EXISTS sql_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(36),
    original_question TEXT NOT NULL,
    generated_sql TEXT NOT NULL,
    validated BOOLEAN DEFAULT FALSE,
    executed BOOLEAN DEFAULT FALSE,
    row_count INT DEFAULT 0,
    execution_ms INT DEFAULT 0,
    rejected_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sql_audit_log_user_id ON sql_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_sql_audit_log_created_at ON sql_audit_log(created_at);
